truecharts/containers

mirror/paperless-ng/Dockerfile

Only merge after https://github.com/truecharts/apps/pull/1552 is done.

feat(paperless-ng): change to official docker image

---

mirror/airsonic-advanced/Dockerfile
mirror/airsonic-advanced/PLATFORM

Reason for the `edge` and not `stable` tag, is that `stable` is almost 2 years old. 
Upstream only do releases in `edge`

feat(airsonic-advanced): add official image

---

mirror/joplin-server/Dockerfile

According to this: https://discourse.joplinapp.org/t/joplin-server-tag-latest-update/19137
Whole project is considered beta for now, so there will only be "beta" docker images.

update joplin-server image

---

mirror/deluge/Dockerfile

They seem to released semver tags (this is the first on this image). Hopefully it will stay that way

update deluge image

---

mirror/deemix/Dockerfile
mirror/deemix/PLATFORM

As per https://github.com/truecharts/apps/pull/1933#discussion_r812116376 
a mirror for deemix docker for PR https://github.com/truecharts/apps/pull/1933

Add Deemix mirror dockerfile

---

mirror/boinc/Dockerfile

LSIO seems to have switched from calver to semver, and now the semver is 7.x.x, which will always be lower than 18.x.x

use boinc latest.

---

mirror/deconz/Dockerfile

original maintainer is AWOL :O, and no one had/has access to CI to add credits, so they forced to create a new "community" repo

change deconz repo

---

mirror/couchpotato/Dockerfile

Couchpotato is deprecated both upstream and from lsio. (repos are archived)
This is the last image update. Let's at least have it up to date.
The specific tags was just commit hashes, not semver or calver. Thats why latest is used here

last update to couchpotato

---

.github/workflows/containers.build.yaml

kimai has `apache-` infront of version.
This should remove it, right?

adjust version tag for kimai

---

mirror/heimdall/Dockerfile

https://github.com/linuxserver/docker-heimdall/pkgs/container/heimdall/17672264?tag=version-v2.4.8

fix(heimdall): Modification of naming rules

---

mirror/nextcloud/Dockerfile

⚒️ Fixes 
https://github.com/truecharts/apps/issues/2984
Add execute permissions to nextcloud `includes/` scripts.
When deploying the latest nextcloud image on TrueNAS scale (`24.0.2_14.0.10`):
```text
tccr.io/truecharts/nextcloud:v24.0.2@sha256:910679f20019efe8b2e80daf225e2c9ebd0577315d75e67eebf3b056654b4ab7
```
... the following error occurs:
```text
2022-06-25T18:46:08.759338526Z /entrypoint.sh: 222: exec: sh /jumpstart.sh: not found
```
The issue can be reproduced by running the following command:
```shell
docker run -it --entrypoint "sh /jumpstart.sh" tccr.io/truecharts/nextcloud:v24.0.2@sha256:910679f20019efe8b2e80daf225e2c9ebd0577315d75e67eebf3b056654b4ab7
```
`ls -l` inside the container reveals that the execute bits are missing from the includes scripts.
```text …
```

nextcloud: chmod +x `includes/` scripts

---

mirror/linkace/Dockerfile

Makes `/app/.env` writable, so the user doesn't have to use the container shell and `chmod` to be able to finish the initial Linkace setup.
**📃 Notes:**

fix(linkace): `chmod a+w /app/.env`

---

.github/renovate.json5
mirror/photoprism/Dockerfile

Based on discussion with app maintainer,  the preferred docker image for photoprism has moved from debian based (bullseye) targets to ubuntu (jammy) targets. The debian based docker targets are no longer feature complete!
⚒️ Fixes  # 
Target change for docker image. 
Tested locally
**📃 Notes:**
- [✔️ ] ⚖️ My code follows the style guidelines of this project
- [ ✔️] 👀 I have performed a self-review of my own code
- [ ✔️] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ✔️] 📄 I have made corresponding changes to the documentation
- [ ✔️] ⚠️ My changes generate no new warnings
- [✔️ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works …

fix(images): update photoprism/photoprism docker tag to v221105-jammy

---

mirror/ipfs/Dockerfile

ipfs/go-ipfs has changed names, new default is now kubo.
⚒️ Fixes  #[4677](https://github.com/truecharts/charts/issues/4677)
**📃 Notes:**
---

feat(ipfs) update upstream image to kubo

---

mirror/kitchenowl-backend/Dockerfile
mirror/kitchenowl-web/Dockerfile

set containers from beta to latest tag.
⚒️ Fixes  #https://github.com/truecharts/charts/issues/5845
**📃 Notes:**
---

fix(kitchenowl) set to latest tag

---

mirror/sickgear/Dockerfile

Use the official image for sickgear instead of the LinuxServer.io image.
Pulled the image locally and tested on my TrueNAS SCALE system with my existing /config PVC.
**📃 Notes:**
This image supports /config as well as the PUID and PGID environment variables.  It seems like a drop-in to avoid the slow chown start up issues in BlueFin.
---
---
I wasn't sure if a change in truecharts/charts would be required …

fix(images): move ghcr.io/linuxserver/sickgear to sickgear/sickgear

---

mirror/plex/Dockerfile

When connecting to the Plex app's container with the shell, an error is printed about parsing an octal value for the umask.  The problem is that the /etc/bash.bashrc file ends with "umask 2umask 2" because both the upstream Dockerfile and this Dockerfile do not include newlines when adding the umask command to /etc/bash.bashrc.  The full fix won't be realized until upstream changes as well, but I opened [this PR there](https://github.com/onedr0p/containers/pull/134) so I don't think working around the issue here is strictly necessary.
⚒️ Fixes
No open issue, but the umask set in the Dockerfile for the /etc/bash.bashrc is not being honored.
Not at all.  But the risk is also incredibly low.
**📃 Notes:**
Waiting on [an …

fix(plex): Add newline to printf of umask

---

mirror/valheim-server/Dockerfile

Updating Valheim server container to be in-sync with latest digest: https://github.com/lloesche/valheim-server-docker/pkgs/container/valheim-server
This specific change is required to have this application usable when user configures Valheim Plus.
Latest official version of Valheim Plus is incompatible with the latest game version. Unofficial fix was made and valheim-server added support for configuring of repository via env variable in [this merged PR](https://github.com/lloesche/valheim-server-docker/pull/599). 

fix(images): Update valheim-server latest to 65fcb2c

---

mirror/socat/Dockerfile

⚒️ Fixes  # 
Haven't raised an issue but changing the base image as it is quite stale (7 years old on docker hub).
It hasn't been. Not sure if it's needed I just copied the new image base from docker hub. I use the same image and tag for https://github.com/truecharts/charts/pull/9287.
**📃 Notes:**
Specifically making this PR so I can use the image in https://github.com/truecharts/charts/pull/9287
Not sure if I need to do anything else to get this image release in tccr.io. Let me know if so.
---
Those checkboxes are there for …

feat(socat): Change stale base

---

mirror/prometheus-config-reloader/Dockerfile

Update to the latest upstream Prometheus Operator prometheus-config-reloader.
https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.66.0
⚒️ Fixes  # 
**📃 Notes:**
---

fix(images): Update prometheus-config-reloader

---

mirror/doublecommander/Dockerfile

This container was last updated a year ago (see screenshot) below so might be a breaking change for some, I actually tested it as a direct replacement using `k3s kubectl edit deploy` and changing the image and worked fine, so we should label this a break change before merging on the `charts` repo.
⚒️ Fixes  # 
**📃 Notes:**
---

fix(doublecommander): Update EXTREMELY old container

---

mirror/tdarr_node/Dockerfile

Add missing 2.00.20, aka the last version SCALE supports
⚒️ Fixes  # 
**📃 Notes:**
---

feat(tdarr_node): Add missing container

---

mirror/minecraft-java/Dockerfile
mirror/minecraft-java11-jdk/Dockerfile
mirror/minecraft-java11-openj9/Dockerfile
mirror/minecraft-java11/Dockerfile
mirror/minecraft-java17-alpine/Dockerfile
mirror/minecraft-java17-graalvm-ce/Dockerfile
mirror/minecraft-java17-jdk/Dockerfile
mirror/minecraft-java17-openj9/Dockerfile
mirror/minecraft-java20-alpine/Dockerfile
mirror/minecraft-java20/Dockerfile
mirror/minecraft-java8-graalvm-ce/Dockerfile
mirror/minecraft-java8-jdk/Dockerfile
mirror/minecraft-java8-openj9/Dockerfile
mirror/minecraft-java8/Dockerfile

bump chart version.
the following images do not get a semver image in our quay backend.
-java8
-graalvm-ce
-java11
-java17-jdk
-java17-graalvm-ce
-java20
-java20-apline
⚒️ Fixes  # 
**📃 Notes:**
---

fix(minecraft-java) bump version

---

apps/nextcloud-fpm/configure-scripts/occ-preview-generator.sh

When using the Nextcloud Memories app, errors related to wrong data types in the config occur, e.g. "Invalid type for system config preview_max_x, expected integer, got string". This PR appends flags to the Preview Generation Configuration to set related values to type `integer` instead of string.
⚒️ Fixes  truecharts/charts#21465
- open shell of the nextcloud container
- manually execute:
```
occ config:system:set jpeg_quality --value="60" --type=integer
occ config:system:set preview_max_x --value="2048" --type=integer
occ config:system:set preview_max_y --value="2048" --type=integer
occ config:system:set preview_max_memory --value="1024" --type=integer
occ config:system:set preview_max_filesize_image --value="50" …
```

fix(nextcloud): use correct data type for image preview config
