mirror/collabora/Dockerfile
=> fix(collabora-online): change to the new versioning format

mirror/guacamole-client/Dockerfile, mirror/guacamole-client/PLATFORM, mirror/guacamole-server/Dockerfile, mirror/guacamole-server/PLATFORM
Preparations for my todo list :)
=> feat(guacamole-*): Add apache guacamole images

mirror/trilium-notes/Dockerfile, mirror/trilium-notes/PLATFORM
Related: https://github.com/truecharts/apps/pull/1715
=> Add Trilium Notes

mirror/beets/Dockerfile, mirror/booksonic-air/Dockerfile, mirror/cloud9/Dockerfile, mirror/digikam/Dockerfile, mirror/doublecommander/Dockerfile, mirror/fireflyiii-core/Dockerfile, mirror/freshrss/Dockerfile, mirror/grav/Dockerfile, mirror/healthchecks/Dockerfile, mirror/heimdall/Dockerfile, mirror/librespeed/Dockerfile, mirror/mstream/Dockerfile, mirror/mylar3/Dockerfile, mirror/oscam/Dockerfile, mirror/piwigo/Dockerfile, mirror/pyload/Dockerfile, mirror/remmina/Dockerfile, mirror/sickgear/Dockerfile, mirror/smokeping/Dockerfile, mirror/sqlitebrowser/Dockerfile, mirror/tvheadend/Dockerfile
Changed some LSIO tags to SemVer (they seem to have started publishing SemVer!). And couple just changed the tag hopping CI will pick them up
=> update some images and change their tag

mirror/librephotos-backend/Dockerfile, mirror/librephotos-frontend/Dockerfile, mirror/librephotos-proxy/Dockerfile
I'm surprised that it worked before :O
=> fix librephotos tags

.github/workflows/containers.build.yaml
Based on https://github.com/reviewdog/action-hadolint#hadolint_ignore
Fix for #128
=> Ingore DL3007 globally

mirror/focalboard/Dockerfile
let's leave it pending until I do some rework (couple days probably) on the app to be able to correctly use official image.
=> use official image

mirror/grist/Dockerfile
After opening an issue, they quickly addressed tags being outdated :)
=> grist - use pinned tag

mirror/flexget/Dockerfile, mirror/flexget/PLATFORM
=> mirror flexget

mirror/qinglong/Dockerfile, mirror/qinglong/PLATFORM
https://hub.docker.com/r/whyour/qinglong
=> Add qinglong

mirror/zerotier/Dockerfile, mirror/zerotier/PLATFORM
=> add zerotier

apps/truecharts-release/Dockerfile, dev/devcontainer/Dockerfile
Reverts truecharts/containers#620
=> Revert "feat(images): update quay.io/helmpack/chart-releaser to v1.4.0"

mirror/mosdns/Dockerfile, mirror/mosdns/PLATFORM
=> feat(mosdns): mirror mosdns

mirror/meshcentral/Dockerfile, mirror/meshcentral/PLATFORM
=> feat(meshcentral): Mirror meshcentral

mirror/mylar3/Dockerfile
=> bump mylar3

mirror/typecho/Dockerfile, mirror/typecho/PLATFORM
=> feat(typecho): mirror typecho

mirror/fancyindex/Dockerfile, mirror/fancyindex/PLATFORM
=> Feat (fancyindex): Add fancyindex

mirror/ipfs/Dockerfile
=> change ipfs upstream image

mirror/statping/Dockerfile
=> fix(statping): change to -ng image

mirror/dokuwiki/Dockerfile
=> switch to bitnami dokuwiki

mirror/fluidd/Dockerfile, mirror/fluidd/PLATFORM
=> add fluidd

mirror/ddns-updater/Dockerfile, mirror/ddns-updater/PLATFORM
=> add ddns-updater

.github/renovate.json5, mirror/authentik/Dockerfile, mirror/authentik/PLATFORM
=> rss bridge renovate

.github/renovate.json5, mirror/baserow/Dockerfile, mirror/baserow/PLATFORM, mirror/zabbix-server/Dockerfile, mirror/zabbix-server/PLATFORM, mirror/zabbix-snmptraps/Dockerfile, mirror/zabbix-snmptraps/PLATFORM, mirror/zabbix-web/Dockerfile, mirror/zabbix-web/PLATFORM
=> add baserow and zabbix

mirror/geoipupdate/Dockerfile, mirror/geoipupdate/PLATFORM
=> add geoipupdate

mirror/inventree/Dockerfile, mirror/inventree/PLATFORM
=> add inventree

.github/renovate.json5, mirror/netdata/Dockerfile, mirror/netdata/PLATFORM
=> add netdata and fix versioning on 2 apps

mirror/adguard-home/Dockerfile, mirror/cups-server/Dockerfile, mirror/cups-server/PLATFORM
=> add cups-server

mirror/rsshub/Dockerfile
=> Update Dockerfile rsshub, digest pin to latest

.github/renovate.json5
=> fix kopia versioning

mirror/airsonic-advanced/Dockerfile
=> fix(airsonic adv): Switch to tag latest

.github/renovate.json5, mirror/commento-plusplus/Dockerfile, mirror/commento-plusplus/PLATFORM, mirror/fileflows/Dockerfile, mirror/fileflows/PLATFORM, mirror/homarr/Dockerfile, mirror/homarr/PLATFORM, mirror/jellyseerr/Dockerfile, mirror/jellyseerr/PLATFORM, mirror/meshroom/Dockerfile, mirror/meshroom/PLATFORM
=> Add containers

.github/renovate.json5, mirror/zabbix-agent/Dockerfile, mirror/zabbix-agent/PLATFORM, mirror/zabbix-agent2/Dockerfile, mirror/zabbix-agent2/PLATFORM
=> fix frigate and zabbix regex

mirror/theme-park/Dockerfile, mirror/theme-park/PLATFORM
Add theme-park reference for mirroring image.
⚒️ Fixes  # 
**📃 Notes:**
=> Add theme-park

mirror/kopia/Dockerfile, mirror/zabbix-server/Dockerfile, mirror/zabbix-snmptraps/Dockerfile, mirror/zabbix-web/Dockerfile
=> zabbix/kopia: change tag format

.github/renovate.json5, mirror/awesome-ttrss/Dockerfile, mirror/awesome-ttrss/PLATFORM, mirror/scrutiny/Dockerfile
=> replace scrutiny image

.github/workflows/containers.build.yaml
=> fix senseai tag generation

mirror/frigate-nvidia/Dockerfile, mirror/kopia/Dockerfile, mirror/scrutiny/Dockerfile, mirror/senseai-server/Dockerfile
=> rebuild Images

mirror/openspeedtest/Dockerfile, mirror/openspeedtest/PLATFORM
=> add openspeedtest

mirror/privatebin/Dockerfile, mirror/privatebin/PLATFORM
=> add privatebin

mirror/wg-easy/Dockerfile, mirror/wg-easy/PLATFORM
Adding WG-easy to our repository
⚒️ Fixes  # 
**📃 Notes:**
=> Adding WG-Easy to the repository

mirror/etesync/Dockerfile, mirror/etesync/PLATFORM
Add EteSync container
⚒️ Fixes
**📃 Notes:**
=> feat(image): add EteSync

mirror/radicale/Dockerfile, mirror/radicale/PLATFORM
Add Radicale Docker image
⚒️ Fixes  # 
**📃 Notes:**
=> Add Radicale image

.github/renovate.json5, mirror/cloudflared/Dockerfile, mirror/cloudflared/PLATFORM, mirror/cloudflareddns/Dockerfile, mirror/cloudflareddns/PLATFORM
=> add cloudflared and ddns images

mirror/plausible/Dockerfile, mirror/plausible/PLATFORM
Add Plausible image
⚒️ Fixes  # 
**📃 Notes:**
=> Add Plausible image

mirror/mineos/Dockerfile, mirror/mineos/PLATFORM
added the mineos files to the mirror dir
-->
⚒️ Fixes  # 
**📃 Notes:**
=> feat(mineos): add mineos #3057

mirror/clickhouse/Dockerfile, mirror/clickhouse/PLATFORM
Add ClickHouse (required for Plausible)
⚒️ Fixes  # 
**📃 Notes:**
=> feat(clickhouse): Add ClickHouse image

mirror/czkawka/Dockerfile
=> pin vers Czkawka

mirror/avidemux/Dockerfile, mirror/avidemux/PLATFORM, mirror/dupeguru/Dockerfile, mirror/dupeguru/PLATFORM, mirror/filebot/Dockerfile, mirror/filebot/PLATFORM, mirror/mediainfo/Dockerfile, mirror/mediainfo/PLATFORM, mirror/mkvcleaver/Dockerfile, mirror/mkvcleaver/PLATFORM, mirror/putty/Dockerfile, mirror/putty/PLATFORM, mirror/qdirstat/Dockerfile, mirror/qdirstat/PLATFORM, mirror/tsmuxer/Dockerfile, mirror/tsmuxer/PLATFORM
=> add 8 apps

mirror/ariang/Dockerfile, mirror/ariang/PLATFORM
=> feat(Ariang): add Ariang

mirror/clickhouse/Dockerfile
Change upstream repo from `yandex/clickhouse-server` to `clickhouse/clickhouse-server`
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(clickhouse): Fix ClickHouse image mirror

mirror/monolithic/Dockerfile, mirror/monolithic/PLATFORM
=> feat(monolithic): Add monolithic

.github/workflows/containers.build.yaml
⚒️ Fixes  # 
Fixes jitsi versioning
**📃 Notes:**
---
=> fix(versioning): drop `stable-`

mirror/minecraftstats/Dockerfile, mirror/minecraftstats/PLATFORM, mirror/plex-meta-manager/Dockerfile, mirror/plex-meta-manager/PLATFORM
adding a new docker app container for minecraftstats
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(minecraftstats): Add minecraftstats

mirror/plex-meta-manager/Dockerfile, mirror/plex-meta-manager/PLATFORM
added the linuxserver/plex-meta-manager container
=> feat(plex-meta-manager): Add plex-meta-manager

mirror/prowlarr/Dockerfile, mirror/readarr/Dockerfile
=> change prowlarr and readarr to develop branches

mirror/bungeecord-java11/Dockerfile, mirror/bungeecord-java11/PLATFORM, mirror/bungeecord-java17/Dockerfile, mirror/bungeecord-java17/PLATFORM, mirror/bungeecord-java8/Dockerfile, mirror/bungeecord-java8/PLATFORM, mirror/bungeecord/Dockerfile, mirror/bungeecord/PLATFORM
Adding standard, java8, java11, java17 containers for bungeecord
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(bungeecord): Add bungeecord

.github/renovate.json5, .github/workflows/containers.build.yaml
=> adjust meshroom's versioning

.github/renovate.json5, .github/workflows/containers.build.yaml
=> adjust bungeecord versioning

.github/workflows/containers.build.yaml
=> fix bungecorde versioning

mirror/ocis/Dockerfile
Current owncloud-ocis release on truecharts is 1.20.0, which is considered an alpha release. The latest releases after that are considered beta releases.
An alternative would be  to use the 'latest' tag, but I haven't checked how often that is updated. The 'latest' tag seems to be updated more often than the official beta releases, as the current latest tag is newer than the current beta release.
Related: https://github.com/truecharts/charts/pull/3256
⚒️ Fixes  # 
**📃 Notes:**
---
Those checkboxes are there for the reviewer …
=> feat(owncloud-ocis): Update owncloud-ocis

mirror/ztcuui-aio/Dockerfile, mirror/ztcuui-aio/PLATFORM
=> feat(ztcuui-aio): add ztcuui-aio

mirror/autobrr/Dockerfile, mirror/autobrr/PLATFORM
Added the container for autobrr
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(autobrr): Add autobrr

.github/renovate.json5, mirror/anki-sync-server/Dockerfile, mirror/anki-sync-server/PLATFORM
=> feat(anki-sync-server): Add anki sync server

mirror/kitchenowl-backend/Dockerfile, mirror/kitchenowl-backend/PLATFORM, mirror/kitchenowl-web/Dockerfile, mirror/kitchenowl-web/PLATFORM, mirror/ts3-manager/Dockerfile, mirror/ts3-manager/PLATFORM
adding new container for ts3-manager
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(ts3-manager): Add ts3-manager

mirror/authentik-ldap/Dockerfile, mirror/authentik-ldap/PLATFORM
=> add authentik-ldap

mirror/mymediaforalexa/Dockerfile, mirror/mymediaforalexa/PLATFORM
add container image
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(mymediaforalexa): Add mymediaforalexa

mirror/rickroll-fhd-game/Dockerfile, mirror/rickroll-fhd-game/PLATFORM, mirror/rickroll-fhd-onclick/Dockerfile, mirror/rickroll-fhd-onclick/PLATFORM, mirror/rickroll-fhd/Dockerfile, mirror/rickroll-fhd/PLATFORM, mirror/rickroll-onclick/Dockerfile, mirror/rickroll-onclick/PLATFORM
add the additonal rickroll images.
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(rickroll): Add rickroll images

mirror/crowdsec-agent/Dockerfile, mirror/crowdsec-agent/PLATFORM, mirror/drone-runner-kube/Dockerfile, mirror/drone-runner-kube/PLATFORM, mirror/traefik-crowdsec-bouncer/Dockerfile, mirror/traefik-crowdsec-bouncer/PLATFORM
=> add crowdsec and drone-runner-kube

mirror/authentik-proxy/Dockerfile, mirror/authentik-proxy/PLATFORM
=> add authentik proxy outpost

mirror/ring-mqtt/Dockerfile
setting a stable versioning for ring-mqtt
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(ring-mqtt): set stable version

mirror/iredmail/Dockerfile, mirror/iredmail/PLATFORM
=> feat(iredmail): Add iredmail

mirror/block-frontend/Dockerfile, mirror/block-frontend/PLATFORM, mirror/blocky/Dockerfile, mirror/blocky/PLATFORM
=> add blocky and blocky-frontend image

mirror/blocky-frontend/Dockerfile
=> fix blocky front

mirror/nextcloud/Dockerfile
⚒️ Fixes  # 
**📃 Notes:**
Adds `exiftool` in order for [this app to work](https://github.com/pulsejet/memories).
I find the default Photos app of NC very lacking. This seems a nice alternative.
---
=> feat(nextcloud): add exiftool package

mirror/theme-park/Dockerfile
Update theme-park version. The update is ~5 days old, and I'm not sure why the bot didn't auto bump this.
⚒️ Fixes  # 
No specific testing done as it should be straightforward minor container update
**📃 Notes:**
---
=> fix(images): update theme-park version

mirror/umami/Dockerfile, mirror/umami/PLATFORM
=> feat(umami): Add umami

.github/workflows/containers.build.yaml
=> append `.0` if version tag is in `Major.Minor` format

mirror/jupyter-all-spark/Dockerfile, mirror/jupyter-all-spark/PLATFORM, mirror/jupyter-base/Dockerfile, mirror/jupyter-base/PLATFORM, mirror/jupyter-datascience/Dockerfile, mirror/jupyter-datascience/PLATFORM, mirror/jupyter-minimal/Dockerfile, mirror/jupyter-minimal/PLATFORM, mirror/jupyter-pyspark/Dockerfile, mirror/jupyter-pyspark/PLATFORM, mirror/jupyter-r/Dockerfile, mirror/jupyter-r/PLATFORM, mirror/jupyter-scipy/Dockerfile, mirror/jupyter-scipy/PLATFORM, mirror/jupyter-tensorflow/Dockerfile, mirror/jupyter-tensorflow/PLATFORM
=> add jupyter imges

mirror/kavitaemail/Dockerfile
email relay server for kavita, setting a specific version
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(kavitaemail): set specific version

mirror/retrobot/Dockerfile, mirror/retrobot/PLATFORM
=> feat(retrobot): Add retrobot

base/ubuntu/latest-version.sh
=> fix latest version script for ubuntu

mirror/immich-ml/Dockerfile, mirror/immich-ml/PLATFORM, mirror/immich-proxy/Dockerfile, mirror/immich-proxy/PLATFORM, mirror/immich-server/Dockerfile, mirror/immich-server/PLATFORM, mirror/immich-web/Dockerfile, mirror/immich-web/PLATFORM
=> add immich

mirror/redisinsight/Dockerfile
=> fix(redisinsight) set stable versioning

mirror/fireflyiii-fidi/Dockerfile, mirror/fireflyiii-fidi/PLATFORM
=> feat(fidi) add fireflyiii-data-importer

mirror/zabbix-java-gateway/Dockerfile, mirror/zabbix-java-gateway/PLATFORM, mirror/zabbix-web-service/Dockerfile, mirror/zabbix-web-service/PLATFORM
=> add zabbix iamges

mirror/raspberrymatic/Dockerfile, mirror/raspberrymatic/PLATFORM
=> feat(raspberrymatic) add raspberrymatic

mirror/retrobot/Dockerfile
Upstream project finally released their own image.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(retrobot) change to upstream image

mirror/nginx-proxy-manager/Dockerfile, mirror/nginx-proxy-manager/PLATFORM
=> add(NPM) add nginx-proxy-manager

mirror/speedtest-tracker/Dockerfile
Change upstream image to a different build.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(speedtest-tracker) change upstream image

mirror/recyclarr/Dockerfile
version was 20 days/ 2 months behind the current version
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(recyclarr) set static ver 2.6.1

mirror/strapi/Dockerfile
Upgrade to v4 
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(strapi) upgrade to v4

mirror/rcon-webadmin/Dockerfile
upgrade image to a static version.
⚒️ Fixes  # 
**📃 Notes:**
---
=> set static version 0.14.1-1

mirror/channels-dvr/Dockerfile, mirror/channels-dvr/PLATFORM
⚒️ Fixes  #1377
**📃 Notes:**
---
=> Add channels-dvr

mirror/ps3netsrv/Dockerfile
switch from latest to fixed version.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(ps3netsrv) set stable version

mirror/euterpe/Dockerfile
=> fix(euterpe) set stable version

mirror/wordpress/Dockerfile, mirror/wordpress/PLATFORM
add wordpress image
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(wordpress) add wordpress

mirror/libremdb/Dockerfile, mirror/libremdb/PLATFORM
=> feat(libremdb) add libremdb mirror

mirror/channels-dvr-tve/Dockerfile, mirror/channels-dvr-tve/PLATFORM
⚒️ Fixes  https://github.com/truecharts/charts/pull/4527#issuecomment-1332360794
**📃 Notes:**
---
=> feat(channels-dvr) Add TV Everywhere image option

mirror/owntracks/Dockerfile, mirror/owntracks/PLATFORM
=> Add Owntracks

mirror/pingvin-share/Dockerfile, mirror/pingvin-share/PLATFORM
=> feat(pingvin-share) add pingvin-share container

mirror/mc-backup/Dockerfile, mirror/mc-backup/PLATFORM
=> feat(mc-backup) add mc-backup container

mirror/wizarr/Dockerfile, mirror/wizarr/PLATFORM
=> feat(wizarr) add wizarr image

mirror/serpbear/Dockerfile, mirror/serpbear/PLATFORM
=> feat(serpbear) add serpbear

mirror/homebox/Dockerfile, mirror/homebox/PLATFORM
=> feat(homebox) add homebox

mirror/jackett2telegram/Dockerfile, mirror/jackett2telegram/PLATFORM
=> feat(jackett2telegram) add jackett2telegram

mirror/lama-cleaner-cpu/Dockerfile, mirror/lama-cleaner-cpu/PLATFORM, mirror/lama-cleaner-gpu/Dockerfile, mirror/lama-cleaner-gpu/PLATFORM
cpu + gpu container images
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(lama-cleaner) add lama-cleaner cpu/gpu

mirror/rstudio/Dockerfile
=> feat(rstudio) set smver 4.2.2

.github/renovate.json5, mirror/jenkins/Dockerfile
=> fix(jenkin) update tag

mirror/shiori/Dockerfile
=> feat(shiori) change image to upstream

mirror/plexanisync/Dockerfile
=> fix(plexanisync) set tag version 1.3.21

mirror/shoko-server/Dockerfile
=> feat(shoko-server) set tag version v4.1.2

mirror/openbooks/Dockerfile, mirror/openbooks/PLATFORM
=> feat(openbooks) add openbooks

mirror/heimdall/Dockerfile
=> fix(heimdall) set tag version to 2.5.5

mirror/ersatztv-nvidia/Dockerfile, mirror/ersatztv-nvidia/PLATFORM, mirror/ersatztv-vaapi/Dockerfile, mirror/ersatztv-vaapi/PLATFORM, mirror/ersatztv/Dockerfile, mirror/ersatztv/PLATFORM
=> feat(ersatztv) add mirror images

mirror/jfa-go/Dockerfile, mirror/jfa-go/PLATFORM
=> feat(jfa-go) add jfa-go

mirror/traefik-forward-auth/Dockerfile, mirror/traefik-forward-auth/PLATFORM
Adding traefik-forward-auth to the image mirror for further development and testing of the chart of the same name.
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(traefik-forward-auth): add traefik-forward-auth

mirror/plexripper/Dockerfile
=> fix(plexripper) set tag version to v0.9.1

mirror/rhasspy/Dockerfile, mirror/rhasspy/PLATFORM
=> feat(rhasspy) add rhasspy

mirror/minecraft-java11-jdk/Dockerfile, mirror/minecraft-java11-jdk/PLATFORM, mirror/minecraft-java11/Dockerfile, mirror/minecraft-java17-alpine/Dockerfile, mirror/minecraft-java17-alpine/PLATFORM, mirror/minecraft-java17-graalvm-ce/Dockerfile, mirror/minecraft-java17-graalvm-ce/PLATFORM, mirror/minecraft-java17-jdk/Dockerfile, mirror/minecraft-java17-jdk/PLATFORM, mirror/minecraft-java17-openj9/Dockerfile, mirror/minecraft-java17-openj9/PLATFORM, mirror/minecraft-java19/Dockerfile, mirror/minecraft-java19/PLATFORM, mirror/minecraft-java8-graalvm-ce/Dockerfile, mirror/minecraft-java8-graalvm-ce/PLATFORM, mirror/minecraft-java8-jdk/Dockerfile, mirror/minecraft-java8-jdk/PLATFORM, mirror/minecraft-java8-openj9/Dockerfile, mirror/minecraft-java8/Dockerfile
=> fix(minecraft-java) tag sub images to static version + new additions

mirror/resilio-sync/Dockerfile
=> fix(resilio-sync) set tag to 2.7.3

mirror/deluge/Dockerfile
=> fix(deluge) update tag to 2.1.1

.github/workflows/containers.build.yaml
This will run the GOSS tests GOSS_ITERATIONS times, waiting for each iteration to complete before starting the next.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(goss ci) add more goss runs

.github/renovate.json5, mirror/homebridge/Dockerfile
=> fix(homebridge) update major 2023-01-08

mirror/wizarr/Dockerfile
Set to ghcr and tagged with a semVer.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(wizarr) change upstream to ghcr and tagged 1.3.1

mirror/plex-debrid/Dockerfile, mirror/plex-debrid/PLATFORM
=> feat(plex-debrid) add plex-debrid

mirror/acestream/Dockerfile
=> fix(acestream) set tagged version to 2.0.2.8

mirror/libreddit/Dockerfile
the original hub image was archived and now replaced with this new official repo.
⚒️ Fixes  # 
**📃 Notes:**
Its possible this might be a major since its been 2 months since the last update on the old image.
---
=> fix(libreddit) change upstream to new repo

mirror/adguardhome-sync/Dockerfile
=> fix(adguardhome-sync) upstream change + semver tag v0.4.12

mirror/tasmoadmin/Dockerfile
=> fix(tasmoadmin) change upstream and set tag v2.4.2

mirror/muse/Dockerfile, mirror/muse/PLATFORM
=> feat(muse) add muse

mirror/upsnap/Dockerfile, mirror/upsnap/PLATFORM
=> feat(upsnap) add upsnap

mirror/anonfiles/Dockerfile, mirror/anonfiles/PLATFORM
=> feat(anonfiles) add anonfiles

mirror/phpmyadmin/Dockerfile
=> fix(phpmyadmin) set tag version to 5.2.1

mirror/apprise-api/Dockerfile
Change to the original project container.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(apprise) change upstream + tag v0.8.3

mirror/ocis/Dockerfile
Update OCIS
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(images): Update OwncloudOCIS to 2.0.0

mirror/unifi-poller/Dockerfile
Changed to the new default upstream container.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(unpoller) changed upstream and tag v2.7.11

.github/renovate.json5, mirror/penpot-backend/Dockerfile, mirror/penpot-exporter/Dockerfile, mirror/penpot-frontend/Dockerfile
=> fix(penpot): penpot removed "beta" and moved to stable from 1.17.0

mirror/somfyprotect2mqtt/Dockerfile, mirror/somfyprotect2mqtt/PLATFORM
=> feat(somfyprotect2mqtt) add somfyprotect2mqtt

mirror/portainer-be/Dockerfile, mirror/portainer-be/PLATFORM
⚒️ Fixes  # 
**📃 Notes:**
- [] ⚖️ My code follows the style guidelines of this project
- [] 👀 I have performed a self-review of my own code
---
=> feat(portainer-be) add portainer-be

mirror/pairdrop/Dockerfile, mirror/pairdrop/PLATFORM
=> feat(pairdrop) add pairdrop

mirror/vaulthunters3/Dockerfile, mirror/vaulthunters3/PLATFORM
3rd edition of the mod.
⚒️ Fixes  # 
**📃 Notes:**
---
=> images(vaulthunters3) add vaulthunters3

mirror/netbootxyz/Dockerfile
=> images(netbootxyz) change upstream

mirror/lldap/Dockerfile, mirror/lldap/PLATFORM
Adding container for LLDAP PR https://github.com/truecharts/charts/pull/7802.
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(lldap) add lldap

mirror/lldap/Dockerfile
Switch to stable tag for lldap as latest has potentially unstable changes not ready for production.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(lldap):switch to stable tag

mirror/notifiarr/Dockerfile, mirror/notifiarr/PLATFORM
=> Add Notifiarr client application

mirror/dell-idrac-fan-controller/Dockerfile, mirror/dell-idrac-fan-controller/PLATFORM
Add the container to mirror
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(dell-idrac-fan-controller): Add Container

mirror/photoprism/Dockerfile
Update branch since we don't need -jammy anymore
⚒️ Fixes  https://github.com/truecharts/charts/issues/8807
**📃 Notes:**
---
=> fix(Photoprism): Update branch for container

.github/renovate.json5
=> update photoprism regex

dev/devcontainer/Dockerfile
=> update helm on dev container

mirror/httpd/Dockerfile, mirror/httpd/PLATFORM, mirror/kube-state-metrics/Dockerfile, mirror/kube-state-metrics/PLATFORM, mirror/node-exporter/Dockerfile, mirror/node-exporter/PLATFORM
These are required for their respective apps
**📃 Notes:**
---
=> add httpd, kube-state-metrics and node-exporter

mirror/whisper-asr-webservice-cpu/Dockerfile, mirror/whisper-asr-webservice-cpu/PLATFORM, mirror/whisper-asr-webservice-gpu/Dockerfile, mirror/whisper-asr-webservice-gpu/PLATFORM
add cpu and gpu images.
⚒️ Fixes  # 
**📃 Notes:**
---
=> image(whisper-asr-webservice) add whisper-asr-webservice

mirror/whisper-asr-webservice-cpu/Dockerfile
=> image(whisper-asr-webservice) use amd64 sha

mirror/frigate/Dockerfile
⚒️ Fixes  # 
Frigate docker images are no longer pushed to Dockerhub per: https://github.com/blakeblackshear/frigate/releases/tag/v0.12.0
**📃 Notes:**
---
=> feat(frigate) switch to new docker source

mirror/firezone/Dockerfile, mirror/firezone/PLATFORM
=> image(firezone) add firezone

mirror/authentik-radius/Dockerfile, mirror/authentik-radius/PLATFORM
=> add authentik radius

mirror/mc-router/Dockerfile, mirror/mc-router/PLATFORM
add mc-router
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(mc-router) add mc-router

mirror/tauticord/Dockerfile, mirror/tauticord/PLATFORM
=> feat(tauticord) add tauticord

mirror/oscam/Dockerfile
=> chore(oscam) bump image version to 11719-ls75

mirror/seafile/Dockerfile, mirror/seafile/PLATFORM
The container used is deprecated and not used, so updating as per https://hub.docker.com/r/seafileltd/seafile-mc/tags
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(seafile): Update container used

mirror/sftpgo/Dockerfile
=> fix(sftpgo): Fix mirror/versionning

mirror/prometheus-operator/Dockerfile
Update to the latest upstream Prometheus Operator.
https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.66.0
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(images): Update prometheus-operator

mirror/qbitmanage/Dockerfile
⚒️ Fixes  #24943
**📃 Notes:**
---
=> chore(qbit_manage) update qbit_manage v4.0.2

mirror/hubleys-dashboard/Dockerfile, mirror/hubleys-dashboard/PLATFORM
=> image(hubleys-dashboard) add hubleys-dashboard

mirror/twingate-connector/Dockerfile, mirror/twingate-connector/PLATFORM
=> image(twingate-connector) add twingate-connector

mirror/gravity/Dockerfile, mirror/gravity/PLATFORM
=> image(gravity) add gravity

mirror/speedtest-tracker/Dockerfile
=> chore(speedtest-tracker) update version to v0.11.17

mirror/siteinspector/Dockerfile, mirror/siteinspector/PLATFORM
=> image(siteinspector) add siteinspector

mirror/buildarr/Dockerfile, mirror/buildarr/PLATFORM
=> feat(buildarr) add buildarr

mirror/ryot/Dockerfile, mirror/ryot/PLATFORM
=> image(ryot) add ryot

mirror/pastey-slim/Dockerfile, mirror/pastey-slim/PLATFORM
=> chore(pastey) update image tag and add slim image

mirror/photostructure/Dockerfile
Latest version of this app.
⚒️ Fixes  # 
**📃 Notes:**
---
=> chore(photostructure) update image to v2.1.0

mirror/local-ai-cublas-cuda11-ffmpeg/Dockerfile, mirror/local-ai-cublas-cuda11-ffmpeg/PLATFORM, mirror/local-ai-cublas-cuda11/Dockerfile, mirror/local-ai-cublas-cuda11/PLATFORM, mirror/local-ai-cublas-cuda12-ffmpeg/Dockerfile, mirror/local-ai-cublas-cuda12-ffmpeg/PLATFORM, mirror/local-ai-cublas-cuda12/Dockerfile, mirror/local-ai-cublas-cuda12/PLATFORM, mirror/local-ai-ffmpeg/Dockerfile, mirror/local-ai-ffmpeg/PLATFORM, mirror/local-ai/Dockerfile, mirror/local-ai/PLATFORM
=> feat(local-ai) add local-ai images

mirror/transmission/Dockerfile
=> chore(transmission) update image to 4.0.3

mirror/tasmobackup/Dockerfile
=> chore(tasmobackupv1) update image to 1.05.0

mirror/wyoming-whisper/Dockerfile, mirror/wyoming-whisper/PLATFORM
⚒️ Fixes  # 
Add [wyoming-whisper](https://github.com/home-assistant/addons/blob/master/whisper/DOCS.md) (STT) for Home Assistant.
**📃 Notes:**
---
=> feat(wyoming-whisper) Add wyoming-whisper

mirror/wyoming-piper/Dockerfile, mirror/wyoming-piper/PLATFORM
⚒️ Fixes  # 
Add [wyoming-piper](https://github.com/home-assistant/addons/blob/master/piper/DOCS.md) (TTS ) for Home Assistant.
**📃 Notes:**
---
=> feat(wyoming-piper) Add wyoming-piper

mirror/slash/Dockerfile, mirror/slash/PLATFORM
=> feat(slash) add slash

mirror/flowise/Dockerfile, mirror/flowise/PLATFORM
=> feat(flowise) add flowise

mirror/fluidd/Dockerfile
Container moved to GHCR, will resume normal updates
⚒️ Fixes  #
**📃 Notes:**
---
=> fix(Fluidd): Update container repository to GHCR

mirror/proxmox-backup-server/Dockerfile, mirror/proxmox-backup-server/PLATFORM
=> feat(pbs) add pbs

mirror/modsecurity-crs-apache/Dockerfile, mirror/modsecurity-crs-apache/PLATFORM, mirror/modsecurity-crs-nginx/Dockerfile, mirror/modsecurity-crs-nginx/PLATFORM
=> feat(modsecurity-crs) add modsecurity-crs

mirror/tdarr_node/Dockerfile
=> fix(tdarr_node): Fix tags/versionning on the node part

mirror/tdarr/Dockerfile
Fixes the tag since they're messing with the versionning
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(Tdarr): Update tag for Tdarr

apps/nextcloud-fpm/Dockerfile
=> update NC dockerfile

mirror/ctfd/Dockerfile, mirror/ctfd/PLATFORM
=> feat(ctfd) add ctfd

mirror/static-web-server/Dockerfile, mirror/static-web-server/PLATFORM
Add Static Web Server
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(static-web-server): add static-web-server

mirror/kaizoku/Dockerfile, mirror/kaizoku/PLATFORM
=> feat(kaizoku) add kaizoku

mirror/homarr/Dockerfile
Fixes -> https://github.com/truecharts/charts/issues/11396
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(homarr): Update to 0.13.1)

mirror/rtorrent-rutorrent-cross-seed/Dockerfile, mirror/rtorrent-rutorrent-cross-seed/PLATFORM
⚒️ Fixes  # 
- [ ✔️] 🪛 Bugfix
Testing was done in https://github.com/truecharts/charts/pull/11594  but this needs to be pulled 
-->
**📃 Notes:**
- [✔️ ] ⚖️ My code follows the style guidelines of this project
- [✔️ ] 👀 I have performed a self-review of my own code
- [✔️ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [✔️ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ✔️] 🖼️ I have added an icon in the Chart's root directory called `icon.png`
---
_Please don't blindly check all the boxes. …
=> New app: rtorrent-rutorrent-cross-seed

mirror/llama-gpt-api/Dockerfile, mirror/llama-gpt-api/PLATFORM, mirror/llama-gpt-ui/Dockerfile, mirror/llama-gpt-ui/PLATFORM
=> feat(llama-gpt) add llama-gpt

mirror/apprise-api/Dockerfile
v1.2.0 does not exist.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(apprise) set version to v0.9.3

mirror/headphones/Dockerfile
=> image(headphones) bump version.

mirror/jellystat/Dockerfile, mirror/jellystat/PLATFORM
=> feat(jellystat) add jellystat

mirror/traefik/Dockerfile
=> Use jramsgz fork for traefik-real-ip middleware plugin

README.md
Makes it clearer for new people where the built images are going :)
⚒️ Fixes  # 
**📃 Notes:**
---
=> Update README.md with quay.io registry URL

.github/renovate.json5, mirror/scrypted-full/Dockerfile, mirror/scrypted-lite/Dockerfile, mirror/scrypted-thin/Dockerfile
=> images(scrypted) update scrypted and fix regex

mirror/romm/Dockerfile
=> image(romm) update to 1.10 ghcr

mirror/slash/Dockerfile
Image changed + bumped
⚒️ Fixes  # 
**📃 Notes:**
---
=> image(slash) update to 0.4.3

mirror/easyshortener/Dockerfile, mirror/easyshortener/PLATFORM
=> feat(easyshortener) add easyshortener

mirror/automatic-ripping-machine/Dockerfile, mirror/automatic-ripping-machine/PLATFORM
=> feat(automatic-ripping-machine) add automatic-ripping-machine

mirror/qbitrr/Dockerfile, mirror/qbitrr/PLATFORM
Add qbitrr container
⚒️ Fixes  #
**📃 Notes:**
---
=> add(qbitrr): add qbitrr container

mirror/homebridge/Dockerfile
They switched names and only publish on DockerHub now
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(Homebridge): Update repo/versioning

mirror/plex-playlist-sync/Dockerfile, mirror/plex-playlist-sync/PLATFORM
Hello, this is my attempt at adding Plex Playlist Sync to the TrueCharts Container Repository in regards to https://github.com/truecharts/charts/pull/12166.
Untested.
**📃 Notes:**
---
=> add(plex-playlist-sync): add Plex Playlist Sync container

mirror/sonsoftheforest/Dockerfile, mirror/sonsoftheforest/PLATFORM
=> image(sonsoftheforest) add sonsoftheforest

mirror/notifiarr/Dockerfile
=> image(notifiarr) set version to 0.6.0

mirror/van-dam/Dockerfile, mirror/van-dam/PLATFORM
=> feat(van-dam) add van-dam

mirror/watcharr/Dockerfile, mirror/watcharr/PLATFORM
=> feat(watcharr) add watcharr

mirror/lancache-prefill/Dockerfile, mirror/lancache-prefill/PLATFORM
=> image(lancache-prefill) add lancache-prefill

mirror/reactive-resume-client/Dockerfile, mirror/reactive-resume-client/PLATFORM, mirror/reactive-resume-server/Dockerfile, mirror/reactive-resume-server/PLATFORM
=> image(reactive-resume) client and server images

mirror/snikket-cert-manager/Dockerfile, mirror/snikket-cert-manager/PLATFORM, mirror/snikket-server/Dockerfile, mirror/snikket-server/PLATFORM, mirror/snikket-web-portal/Dockerfile, mirror/snikket-web-portal/PLATFORM, mirror/snikket-web-proxy/Dockerfile, mirror/snikket-web-proxy/PLATFORM
=> feat(snikket) add snikket images

mirror/zammad/Dockerfile, mirror/zammad/PLATFORM
PR to get Zammad into the TrueCharts Container Repository. Will open a PR in [truecharts/containers](https://github.com/truecharts/containers) soon™.
N/A
**📃 Notes:**
---
=> add(zammad): add Zammad container

mirror/lynx/Dockerfile, mirror/lynx/PLATFORM
=> feat(lynx): add lynx

mirror/gophish/Dockerfile, mirror/gophish/PLATFORM
=> feat(gophish): add gophish

mirror/go-feature-flag-relay-proxy/Dockerfile, mirror/go-feature-flag-relay-proxy/PLATFORM
=> feat(go-feature-flag-relay-proxy): create go-feature-flag-relay-proxy

mirror/flagsmith/Dockerfile, mirror/flagsmith/PLATFORM
=> feat(flagsmith): create flagsmith

mirror/chartbrew/Dockerfile, mirror/chartbrew/PLATFORM
=> feat(chartbrew) add chartbrew

mirror/centrifugo/Dockerfile, mirror/centrifugo/PLATFORM
=> feat(centrifugo) add centrifugo

mirror/blackcandy/Dockerfile, mirror/blackcandy/PLATFORM
=> feat(blackcandy) add blackcandy

mirror/asciinema-server/Dockerfile, mirror/asciinema-server/PLATFORM
=> feat(asciinema-server) add asciinema-server

mirror/answer/Dockerfile, mirror/answer/PLATFORM
=> feat(answer) add answer

mirror/admidio/Dockerfile, mirror/admidio/PLATFORM
=> feat(admidio) add admidio

mirror/2fauth/Dockerfile, mirror/2fauth/PLATFORM
=> feat(2fauth) add 2fauth

mirror/docassemble/Dockerfile, mirror/docassemble/PLATFORM
=> feat(docassemble) add docassemble

mirror/googlephotossync/Dockerfile
Original image is deprecated, this is the latest and active + semver tag
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(googlephotossync) change upstream image

mirror/elasticsearch/Dockerfile, mirror/elasticsearch/PLATFORM
Added the upstream Elasticsearch container from Bitnami. Follow the discussion in the [Discord Server](https://discord.com/channels/830763548678291466/1152627719176192081/1152627722380652545).
⚒️ Fixes  # 
Untested
**📃 Notes:**
---
=> add(elasticsearch): add Elasticsearch container

mirror/backuppc/Dockerfile
=> image(backuppc) set semvar tag 6.0.2

mirror/lynx/Dockerfile
=> fix(lynx) change image to amd64 sha

apps/nextcloud-fpm/latest-version.sh
=> remove fpm

mirror/dendrite-monolith/Dockerfile, mirror/dendrite-monolith/PLATFORM
=> feat(dendrite): add dendrite

mirror/telepush/Dockerfile, mirror/telepush/PLATFORM
=> feat(telepush): add telepush

mirror/pushbits-server/Dockerfile, mirror/pushbits-server/PLATFORM
=> feat(pushbits): add pushbits

mirror/mautrix-discord/Dockerfile, mirror/mautrix-discord/PLATFORM, mirror/mautrix-facebook/Dockerfile, mirror/mautrix-facebook/PLATFORM, mirror/mautrix-gmessages/Dockerfile, mirror/mautrix-gmessages/PLATFORM, mirror/mautrix-googlechat/Dockerfile, mirror/mautrix-googlechat/PLATFORM, mirror/mautrix-instagram/Dockerfile, mirror/mautrix-instagram/PLATFORM, mirror/mautrix-signal/Dockerfile, mirror/mautrix-signal/PLATFORM, mirror/mautrix-slack/Dockerfile, mirror/mautrix-slack/PLATFORM, mirror/mautrix-syncproxy/Dockerfile, mirror/mautrix-syncproxy/PLATFORM, mirror/mautrix-telegram/Dockerfile, mirror/mautrix-telegram/PLATFORM, mirror/mautrix-twitter/Dockerfile, mirror/mautrix-twitter/PLATFORM, mirror/mautrix-whatsapp/Dockerfile, mirror/mautrix-whatsapp/PLATFORM, mirror/mautrix-wsproxy/Dockerfile, mirror/mautrix-wsproxy/PLATFORM
=> feat(mautrix): add mautrix

mirror/remotely/Dockerfile
=> fix(remotely) change remotely upstream image.

mirror/smtp-relay/Dockerfile, mirror/smtp-relay/PLATFORM
=> feat(smtp) add smtp

mirror/restic-rest-server/Dockerfile
=> fix(restic-rest-server) set tag to 0.12.1

apps/jackett/Dockerfile
=> fix(jackett) fix dockerfile

mirror/fileflows/Dockerfile
=> fix(images): Update Fileflows to 23.10

mirror/anki-sync-server/Dockerfile
=> feat(anki-sync-server): Update to non-deprecated container

mirror/frigate-tensorrt/Dockerfile, mirror/frigate-tensorrt/PLATFORM
We need a separate container for TensorRT support, very useful for us, since many users have nvidia GPUs so they can use this instead of a Coral, I'll file a PR for an image selector once this is merged
⚒️ Fixes  # 
**📃 Notes:**
---
=> feat(frigate): Add TensorRT container for nvidia GPUs

mirror/homepage/Dockerfile
The original repo has moved to an organization repository with the name gethomepage. See [this link](https://gethomepage.dev/v0.7.3/more/homepage-move/) for additional details on why this change is needed.
---
=> Homepage has changed home on Github

mirror/decluttarr/Dockerfile, mirror/decluttarr/PLATFORM
=> feat(decluttarr) add decluttarr

mirror/youtubedl-material/Dockerfile
=> feat(youtubedl-material): Update repo to GHCR + new version

mirror/frigate-tensorrt/Dockerfile
=> fix(Frigate): Actually use Tensor RT container

mirror/kubernetes-reflector/Dockerfile, mirror/kubernetes-reflector/PLATFORM
⚒️ Fixes  # 
Adding app image as part of PR https://github.com/truecharts/charts/pull/13756
**📃 Notes:**
---
=> feat(kubernetes-reflector): Add Kubernetes-Reflector

mirror/evershop/Dockerfile, mirror/evershop/PLATFORM
Add the EverShop container to the TCCR. EveryShop is a open-source NodeJS ecommerce platform.
**📃 Notes:**
---
=> feat(evershop): add EverShop

README.md
Updated the README.md file to add instructions for new people who are trying to add containers to the TrueCharts Container Repository before they add new charts in the other repository.
**📃 Notes:**
---
=> Update README.md with PR Instructions

apps/nextcloud-fpm/README.md, apps/nextcloud-fpm/scripts/post-install.sh
⚒️ Fixes  # 
Adding this env to allow force enabling the `allow_local_remote_servers` configuration option.
Not tested. Should work though.
**📃 Notes:**
---
=> feat(nextcloud): Add NX_FORCE_ENABLE_ALLOW_LOCAL_REMOTE_SERVERS env

mirror/external-dns/Dockerfile, mirror/external-dns/PLATFORM
=> feat(external-dns): Add External-DNS container

mirror/cs2/Dockerfile, mirror/cs2/PLATFORM
=> feat(cs2) add cs2

mirror/pocketmine-mp/Dockerfile, mirror/pocketmine-mp/PLATFORM
=> feat(pocketmine-mp) add pocketmine-mp

mirror/borg-server/Dockerfile, mirror/borg-server/PLATFORM
=> feat(borg-server) add borg-server

mirror/qbit-port-forward/Dockerfile, mirror/qbit-port-forward/PLATFORM
Add container for qbit-port-forward
⚒️ Fixes  # 
**📃 Notes:**
---
=> add(qbit-port-forward): add container

mirror/multi-scrobbler/Dockerfile
Changes upstream source from latest to semver.
⚒️ Fixes  # 
**📃 Notes:**
---
=> fix(multi-scrobbler): switch upstream source to semver

apps/nextcloud-fpm/configure-scripts/occ-onlyoffice.sh
=> chore(nextcloud): require the 2 vars

apps/nextcloud-fpm/configure-scripts/occ-onlyoffice.sh
=> fix(nextcloud): fix inverse logic

apps/nextcloud-push-notify/latest-version.sh
=> fix notify push version script

apps/traefik/latest-version.sh
=> fix script

apps/lvm-disk-watcher/Dockerfile, apps/lvm-disk-watcher/includes/watch_lvm.sh
=> remove lvm-watcher config-file watching logic

apps/nextcloud-fpm/scripts/occ
=> fix(nextcloud): correctly handle occ parameter expansion
